global:
  storageClass: "sreworks-hostpath"

  minio:
    accessKey: 'XmizyTRKhgYTrVkK'
    secretKey: 'Df229gtwZ4bssMzK23VJXq9vrGqpxdHA'

  images:
    registry: sreworks-registry.cn-beijing.cr.aliyuncs.com/sreworks
    tag: v0.5

  accessMode: ingress

platformName: SREWorks
platformLogo: /static/publicMedia/sreworks.png

installMode: default

debug: false

images: {}

build:
  isHome: false
  importFrontend: true
  enable: false
  images: {}

core: 
  init: true
  stageId: prod
  appId: flycore

saas:
  init: true
  stageId: prod
  onlyBase: false
  list:
  - cluster
  - app
  - team
  - dataops
  - system
  - job
  - search
  - healing
  - aiops
  - health
  - ocenter
  - help
  - upload
  - demoapp
  baseList:
  - cluster
  - app
  - team
  - system
  - help
  - upload
  - demoapp 
  dataops:
    dbPassword: cb56b5is5e21_c359b42223 
  grafana:
    password: "sreworks123456"

swcli:
  username: superuser
  password: yJfIYmjAiCL0ondV3kY7e5x6kVTpvC3h
  clientId: superclient
  clientSecret: stLCjCPKbWmki65DsAj2jPoeBLPimpJa

source:
  branch: master
  repo: https://code.aliyun.com/sreworks_public/mirror.git

appmanagerbase:
  enabled: true
  redis:
    password: 'siJEULmQYQ' 
 
appmanager:
  enabled: true

  gateway:
    account_super_client_id: common
    account_super_client_secret: common-9efab2399c7c560b34de477b9aa0a465 
    account_super_id: admin
    account_super_secret_key: test-super-secret-key 

  server:
    jvmXMX: "512m"
    docker:
      enableKaniko: true
      account: sreworks
      password: sreworksDocker123q
      registry: registry.cn-zhangjiakou.aliyuncs.com
      namespace: builds




